### ISSUE TITLE
fix GitHub Actions - what file is last_year_fall_biannual_filename?

### ISSUE THREAD

**Issue by ValentineHerr** [SCBI-ForestGEO/Dendrobands#129]
@jess-shue, in [this commit](https://github.com/SCBI-ForestGEO/Dendrobands/commit/fb466c4bb39cbf6c5b0a2187a7eb09a1fadd7370) you added a line of code to read a file whose name is stored in object `last_year_fall_biannual_filename`. That object is not created anywhere in the script so that line of code fails and we can't tell what file you meant to read in. Can you either let @rmh24  know what file you meant to read or fix the script to create that object? Thanks!
See [this comment](https://github.com/SCBI-ForestGEO/Dendrobands/commit/fb466c4bb39cbf6c5b0a2187a7eb09a1fadd7370#r144379235) for detail

**Comment by jess-shue** [comment]
Hi @ValentineHerr and @rmh24,
  I saw your previous comment and that same day I added a line to the 'create_master_csv_2021_and_after.R' script to include the creation of that object. I pushed the code that same day, maybe it hasn't updated? I will try to push it again now and maybe folks should pull the origin?

Sorry, didn't know how to respond to your other comment...

**Comment by ValentineHerr** [comment]
@jess-shue, oh sorry I didn't see you had done something about it. @rmh24 will attempt to figure out why GitHub actions are still failing then. We will be in touch.

**Comment by jess-shue** [comment]
@ValentineHerr I know when that push completed, I still received a GitHub email saying all jobs had failed...so that may not have been enough to fix things.

**Comment by ValentineHerr** [comment]
Thanks @jess-shue. I have fixed the issues, and the GitHub Actions are now working properly. I'll close this issue but will open a new issue to point out the reports the errors in the data that need to be addressed.
